default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: xiamen_development

test:
  <<: *default
  database: xiamen_test

production:
  primary:
    <<: *default
    database: xiamen_production

  cache:
    <<: *default
    database: xiamen_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    database: xiamen_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    database: xiamen_production_cable
    migrations_paths: db/cable_migrate